name: 'Grid.ai Run Checkout'
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  unittests:
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        os: [ubuntu-latest, macos-latest,windows-latest]
        python-version: [3.8,3.9]       
        python-venv: ["","venv"]       
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2     
        with:
          repository: robert-s-lee/hello
      - run:
          echo ${GITHUB_WORKSPACE}
      - uses: gridai-actions/gridai-login@main
        with:
          python-version: ${{ matrix.python-version }}
          python-venv: ${{ matrix.python-venv }}
          gridai-username: ${{ secrets.GRIDAI_USERNAME }} 
          gridai-key: ${{ secrets.GRIDAI_KEY }}
      - uses: gridai-actions/gridai-run@main
        with:
          script-dir: ${GITHUB_WORKSPACE}
          script-name: hello.py
