name: 'Session Ubuntu'
on:
  push:
    paths:
      - action.yml
      - .github/workflows/workflow-session.yml
      - .github/workflows/unittest-ubuntu.yml
jobs:
  cpu-session:
    uses: gridai-actions/gridai-session/.github/workflows/workflow-session.yml@main
    with:
      cluster-name: c211102-192711
      os: ubuntu-latest
      instance-type: t2.medium
    secrets:  
      gridai-username: ${{ secrets.GRIDAI_USERNAME }} 
      gridai-key: ${{ secrets.GRIDAI_KEY }}      
  gpu-session:
    uses: gridai-actions/gridai-session/.github/workflows/workflow-session.yml@main
    with:
      cluster-name: c211102-192711
      os: ubuntu-latest
      instance-type: g4dn.xlarge
    secrets:  
      gridai-username: ${{ secrets.GRIDAI_USERNAME }} 
      gridai-key: ${{ secrets.GRIDAI_KEY }}  