name: 'Session Mac'
on:
  workflow_dispatch:
  push:
    paths:
      - action.yml
      - .github/workflows/workflow-session.yml
      - .github/workflows/unittest-mac.yml
  schedule:
  # run at 13 min past the hour every day
  # MIN HOUR DOM MON DOW CMD
    - cron: 23 4 * * *            
jobs:
  cpu-session:
    uses: gridai-actions/gridai-session/.github/workflows/workflow-session.yml@main
    with:
      os: ubuntu-latest
      instance-type: t2.medium
    secrets:  
      gridai-username: ${{ secrets.GRIDAI_USERNAME }} 
      gridai-key: ${{ secrets.GRIDAI_KEY }}       
