name: 'Session Ubuntu'
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/workflow-session.yml
      - .github/workflows/unittest-ubuntu.yml
  schedule:
  # run at 13 min past the hour every day
  # MIN HOUR DOM MON DOW CMD
    - cron: 23 5 * * *            
jobs:
  create-session:  
    runs-on: ubuntu-latest
    timeout-minutes: 60
    outputs:
      name: ${{ steps.gridai-obj-create.outputs.name }}
    steps:
      - uses: gridai-actions/gridai-login@v0
        with:
          gridai-username: ${{ secrets.GRIDAI_USERNAME }} 
          gridai-key: ${{ secrets.GRIDAI_KEY }} 
      - id: gridai-obj-create
        run: |
          gridai.py create_sess --grid_args " ${GRID_ARGS}" --gha True
      - run: |
          if [ "${{ steps.gridai-obj-create.outputs.match-status }}" != "running" ]; then
            echo "grid session: failed with ${{ steps.gridai-obj-create.outputs.error }}"
            exit 1
          fi

  pause-resume-t2-medium:
    needs: create-session
    uses: gridai-actions/gridai-session/.github/workflows/session-pause-resume.yml@main
    with:
      os: ubuntu-latest
      name: ${{ needs.create-session.outputs.name }}
    secrets:  
      gridai-username: ${{ secrets.GRIDAI_USERNAME }} 
      gridai-key: ${{ secrets.GRIDAI_KEY }}   

  change-t2-large:
    needs: create-session
    uses: gridai-actions/gridai-session/.github/workflows/session-change-instance-type.yml@main
    with:
      os: ubuntu-latest
      instance_type: t2.large
      name: ${{ needs.create-session.outputs.name }}
    secrets:  
      gridai-username: ${{ secrets.GRIDAI_USERNAME }} 
      gridai-key: ${{ secrets.GRIDAI_KEY }}   

  pause-resume-t2-large:
    needs: cpu-session
    uses: gridai-actions/gridai-session/.github/workflows/session-pause-resume.yml@main
    with:
      os: ubuntu-latest
      name: ${{ needs.create-session.outputs.name }}
    secrets:  
      gridai-username: ${{ secrets.GRIDAI_USERNAME }} 
      gridai-key: ${{ secrets.GRIDAI_KEY }}  

  session-delete:
    needs: cpu-session
    uses: gridai-actions/gridai-session/.github/workflows/session-delete.yml@main
    with:
      os: ubuntu-latest
      name: ${{ needs.create-session.outputs.name }}
    secrets:  
      gridai-username: ${{ secrets.GRIDAI_USERNAME }} 
      gridai-key: ${{ secrets.GRIDAI_KEY }}   