name: 'Session Ubuntu'
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/workflow-session.yml
      - .github/workflows/unittest-ubuntu.yml
  schedule:
  # run at 13 min past the hour every day
  # MIN HOUR DOM MON DOW CMD
    - cron: 23 5 * * *            
jobs:
  create_session:  
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: gridai-actions/gridai-login@v0
        with:
          gridai-username: ${{ secrets.GRIDAI_USERNAME }} 
          gridai-key: ${{ secrets.GRIDAI_KEY }} 
      - id: gridai-obj-create
      - run: |
          gridai.py create_sess --grid_args " ${GRID_ARGS}" --gha True
      - run: |
          if [ "${{ steps.gridai-obj-create.outputs.match-status }}" != "running" ]; then
            echo "grid session: failed with ${{ steps.gridai-obj-create.outputs.error }}"
            exit 1
          fi

  cpu-session:
    needs: create_session
    uses: gridai-actions/gridai-session/.github/workflows/workflow-session.yml@main
    with:
      os: ubuntu-latest
      instance_type: t2.medium
    secrets:  
      gridai-username: ${{ secrets.GRIDAI_USERNAME }} 
      gridai-key: ${{ secrets.GRIDAI_KEY }}   

  gpu-session:
    needs: cpu-session
    uses: gridai-actions/gridai-session/.github/workflows/workflow-session.yml@main
    with:
      os: ubuntu-latest
      instance_type: g4dn.xlarge
    secrets:  
      gridai-username: ${{ secrets.GRIDAI_USERNAME }} 
      gridai-key: ${{ secrets.GRIDAI_KEY }}  