name: 'Workflow Session'
on:
  workflow_call:
    inputs:
      # CLI Environment Variations
      os:
        required: true
        type: string 
      instance-type:
        required: true  
        type: string
    secrets:
      # CLI Logins
      gridai-username:
        required: true
      gridai-key:
        required: true
jobs:
  unittests:
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        python-version: [3.8] #,3.9]       
        python-venv: [""]     # ,"venv"]     
        use-spot: [""]        # , "--use_spot"]
    runs-on: ${{ inputs.os }}
    timeout-minutes: 60
    steps:
      - uses: gridai-actions/gridai-login@main
        with:
          python-version: ${{ matrix.python-version }}
          python-venv: ${{ matrix.python-venv }}
          gridai-username: ${{ secrets.gridai-username }} 
          gridai-key: ${{ secrets.gridai-key }} 
      - id: gridai-obj-create
        uses: gridai-actions/gridai-session@main
        with:
          grid-args: "${{ matrix.use-spot }} --instance_type ${{ inputs.instance-type }}"
      - run: | 
          grid session ssh ${{ steps.gridai-obj-create.outputs.obj-id }} "ls; exit" | tee grid.session.log
      - run: |
          grid session pause ${{ steps.gridai-obj-create.outputs.obj-id }} 
      - id: gridai-obj-status-pause
        uses: gridai-actions/gridai-status@main
        with:
          obj-type: session
          obj-id: ${{ steps.gridai-obj-create.outputs.obj-id }}
          script-args: "-t paused"
      - run: |
          grid session resume ${{ steps.gridai-obj-create.outputs.obj-id }}
      - id: gridai-obj-status-resume
        uses: gridai-actions/gridai-status@main
        with:
          obj-type: session
          obj-id: ${{ steps.gridai-obj-create.outputs.obj-id }}
          script-args: "-t running"
      - run: |
          grid session ssh ${{ steps.gridai-obj-create.outputs.obj-id }} "ls; exit" | tee grid.session.log                          
      - run: |
          grid session delete ${{ steps.gridai-obj-create.outputs.obj-id }}
   